services:
  db:
    container_name: gotcha_db
    image: postgres
    environment:
      POSTGRES_USER: ${GOTCHA_DB_USER}
      POSTGRES_PASSWORD: ${GOTCHA_DB_PASS}
      POSTGRES_DB: ${GOTCHA_DB_DATABASE}
    ports:
      - "5432:5432"