services:
  surrealdb:
    container_name: surrealdb
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASS
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
