services:
  surrealdb:
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $GOTCHA_DB_USER
      - --pass
      - $GOTCHA_DB_PASS
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"